### ISSUE TITLE
connecting "compose post" to appwrite Database 

### ISSUE THREAD

**Issue by vedantbahel** [vedantbahel/viteED#29]
Code has already been added to compose a post. Add write functionality to write the post to database on submission.
Find details of appwrite database in readme of root folder of the project.

**Comment by ShivamMenda** [comment]
@vedantbahel I've never worked with appwrite before but I would like to give this a try. Can I take this up and try it out tomorrow if you don't mind?

**Comment by vedantbahel** [comment]
sure. give it a try

**Comment by ShivamMenda** [comment]
@vedantbahel Ill try it out! Thanks

**Comment by Odinachi** [comment]
I'll work on this.

**Comment by vedantbahel** [comment]
Sure

**Comment by Odinachi** [comment]
@vedantbahel  I keep getting this error when I try to post to the database


`E/flutter ( 6156): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: AppwriteException: null, SocketException: Connection timed out (OS Error: Connection timed out, errno = 110), address = 10.0.2.2, port = 43734 (0)
E/flutter ( 6156): #0      ClientIO.call (package:appwrite/src/client_io.dart:364:7)
E/flutter ( 6156): <asynchronous suspension>
E/flutter ( 6156): #1      Account.get (package:appwrite/services/account.dart:20:17)
E/flutter ( 6156): <asynchronous suspension>
E/flutter ( 6156): 
E/flutter ( 6156): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: AppwriteException: null, SocketException: Connection timed out (OS Error: Connection timed out, errno = 110), address = 10.0.2.2, port = 43736 `

**Comment by Rohit-RA-2020** [comment]
> @vedantbahel I keep getting this error when I try to post to the database
> 
> `E/flutter ( 6156): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: AppwriteException: null, SocketException: Connection timed out (OS Error: Connection timed out, errno = 110), address = 10.0.2.2, port = 43734 (0) E/flutter ( 6156): #0 ClientIO.call (package:appwrite/src/client_io.dart:364:7) E/flutter ( 6156): <asynchronous suspension> E/flutter ( 6156): #1 Account.get (package:appwrite/services/account.dart:20:17) E/flutter ( 6156): <asynchronous suspension> E/flutter ( 6156): E/flutter ( 6156): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: AppwriteException: null, SocketException: Connection timed out (OS Error: Connection timed out, errno = 110), address = 10.0.2.2, port = 43736 `

Where are you running the app? Emulator or on real device?

**Comment by Odinachi** [comment]
On an emulator and it is same on a real device.

**Comment by Rohit-RA-2020** [comment]
Seems like there is an issue making connection with appwrite backend. Few things you can try

- Make sure appwrite is running, restart the docker image
- Recheck the endpoint in the settings
- Disable any firewall
- Check database and collection id
